// <auto-generated />
using System;
using Aktien.Data.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Aktien.Data.Migrations
{
    [DbContext(typeof(Infrastructure.Repository))]
    [Migration("20201230165206_4")]
    partial class _4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Data.Entity.AktieEntitys.Aktie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ISIN")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WKN")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Aktie");
                });

            modelBuilder.Entity("Data.Entity.AktieEntitys.Dividende", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AktieID")
                        .HasColumnType("integer");

                    b.Property<double>("Betrag")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("AktieID");

                    b.ToTable("Dividende");
                });

            modelBuilder.Entity("Data.Model.DepotEntitys.Depot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Depot");
                });

            modelBuilder.Entity("Data.Model.DepotEntitys.DepotAktien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AktieID")
                        .HasColumnType("integer");

                    b.Property<int>("Anzahl")
                        .HasColumnType("integer");

                    b.Property<double>("BuyIn")
                        .HasColumnType("double precision");

                    b.Property<int>("DepotID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AktieID");

                    b.HasIndex("DepotID");

                    b.ToTable("DepotAktien");
                });

            modelBuilder.Entity("Data.Model.DepotEntitys.OrderHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AktieID")
                        .HasColumnType("integer");

                    b.Property<int>("Anzahl")
                        .HasColumnType("integer");

                    b.Property<double>("Fremdkostenzuschlag")
                        .HasColumnType("double precision");

                    b.Property<int>("Kaufart")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Kaufdatum")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Orderart")
                        .HasColumnType("integer");

                    b.Property<double>("Preis")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.HasIndex("AktieID");

                    b.ToTable("OrderHistory");
                });

            modelBuilder.Entity("Data.Entity.AktieEntitys.Dividende", b =>
                {
                    b.HasOne("Data.Entity.AktieEntitys.Aktie", "Aktie")
                        .WithMany("Dividenden")
                        .HasForeignKey("AktieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Model.DepotEntitys.DepotAktien", b =>
                {
                    b.HasOne("Data.Entity.AktieEntitys.Aktie", "Aktie")
                        .WithMany()
                        .HasForeignKey("AktieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Model.DepotEntitys.Depot", "Depot")
                        .WithMany("DepotAktien")
                        .HasForeignKey("DepotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Model.DepotEntitys.OrderHistory", b =>
                {
                    b.HasOne("Data.Entity.AktieEntitys.Aktie", "Aktie")
                        .WithMany("OrderHistories")
                        .HasForeignKey("AktieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
