// <auto-generated />
using System;
using Aktien.Data.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Aktien.Data.Infrastructure.Migrations
{
    [DbContext(typeof(Repository))]
    partial class RepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Aktien.Data.Model.DepotModels.Depot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Depot");
                });

            modelBuilder.Entity("Aktien.Data.Model.DepotModels.DepotWertpapier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Anzahl")
                        .HasColumnType("double precision");

                    b.Property<double>("BuyIn")
                        .HasColumnType("double precision");

                    b.Property<int>("DepotID")
                        .HasColumnType("integer");

                    b.Property<int>("WertpapierID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("DepotID");

                    b.HasIndex("WertpapierID");

                    b.ToTable("DepotWertpapier");
                });

            modelBuilder.Entity("Aktien.Data.Model.WertpapierModels.Dividende", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Betrag")
                        .HasColumnType("double precision");

                    b.Property<double?>("BetragUmgerechnet")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Waehrung")
                        .HasColumnType("integer");

                    b.Property<int>("WertpapierID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("WertpapierID");

                    b.ToTable("Dividende");
                });

            modelBuilder.Entity("Aktien.Data.Model.WertpapierModels.DividendeErhalten", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Bestand")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DividendeID")
                        .HasColumnType("integer");

                    b.Property<double>("GesamtBrutto")
                        .HasColumnType("double precision");

                    b.Property<double>("GesamtNetto")
                        .HasColumnType("double precision");

                    b.Property<double?>("Quellensteuer")
                        .HasColumnType("double precision");

                    b.Property<double?>("Umrechnungskurs")
                        .HasColumnType("double precision");

                    b.Property<int>("WertpapierID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("DividendeID");

                    b.HasIndex("WertpapierID");

                    b.ToTable("DividendeErhalten");
                });

            modelBuilder.Entity("Aktien.Data.Model.WertpapierModels.OrderHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Anzahl")
                        .HasColumnType("double precision");

                    b.Property<int>("BuySell")
                        .HasColumnType("integer");

                    b.Property<double?>("Fremdkostenzuschlag")
                        .HasColumnType("double precision");

                    b.Property<int>("KaufartTyp")
                        .HasColumnType("integer");

                    b.Property<int>("OrderartTyp")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Orderdatum")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Preis")
                        .HasColumnType("double precision");

                    b.Property<int>("WertpapierID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("WertpapierID");

                    b.ToTable("OrderHistory");
                });

            modelBuilder.Entity("Aktien.Data.Model.WertpapierModels.Wertpapier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ISIN")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WKN")
                        .HasColumnType("text");

                    b.Property<int>("WertpapierTyp")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Wertpapier");
                });

            modelBuilder.Entity("Aktien.Data.Model.DepotModels.DepotWertpapier", b =>
                {
                    b.HasOne("Aktien.Data.Model.DepotModels.Depot", "Depot")
                        .WithMany("DepotWertpapier")
                        .HasForeignKey("DepotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aktien.Data.Model.WertpapierModels.Wertpapier", "Wertpapier")
                        .WithMany()
                        .HasForeignKey("WertpapierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aktien.Data.Model.WertpapierModels.Dividende", b =>
                {
                    b.HasOne("Aktien.Data.Model.WertpapierModels.Wertpapier", "Wertpapier")
                        .WithMany("Dividenden")
                        .HasForeignKey("WertpapierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aktien.Data.Model.WertpapierModels.DividendeErhalten", b =>
                {
                    b.HasOne("Aktien.Data.Model.WertpapierModels.Dividende", "Dividende")
                        .WithMany()
                        .HasForeignKey("DividendeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aktien.Data.Model.WertpapierModels.Wertpapier", "Wertpapier")
                        .WithMany("ErhalteneDividenden")
                        .HasForeignKey("WertpapierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aktien.Data.Model.WertpapierModels.OrderHistory", b =>
                {
                    b.HasOne("Aktien.Data.Model.WertpapierModels.Wertpapier", "Wertpapier")
                        .WithMany("OrderHistories")
                        .HasForeignKey("WertpapierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
